more profiling and error checking for simulation scripts.
added timing commands to SLURM submit script for profiling.
improved error handling of SLURM scripts.

diff --git a/docker/batch/JavaPreprocessor64 b/docker/batch/JavaPreprocessor64
--- a/docker/batch/JavaPreprocessor64
+++ b/docker/batch/JavaPreprocessor64
@@ -44,9 +44,13 @@ arguments=$*
 
 echo "starting preprocessor"
 
-nice java ${jvmprop} ${preprocessor_mainclass} ${arguments} 
+java ${jvmprop} ${preprocessor_mainclass} ${arguments}
+stat=$?
 
-echo "preprocessor returned"
-
-exit 0
-
+if [[ $stat -ne 0 ]]; then
+	echo "preprocessor failed with exit code $stat"
+	exit $stat
+else
+	echo "preprocessor returned"
+	exit 0
+fi
