compiled solvers ignore "stop" msg, Dispatcher kills in 1 minute.
HtcSimulationWorker should listen to ServiceControl topic for
  simulation stop request and call delete (SLURM scancel).
Currently relies on Dispatcher "zombie killer" task (1/min).
SLURM mock sbatc writes pid to file and scancel kills process,
  untested.

diff --git a/deploy/mockslurm/scancel b/deploy/mockslurm/scancel
--- a/deploy/mockslurm/scancel
+++ b/deploy/mockslurm/scancel
@@ -1,36 +1,29 @@
 #!/usr/bin/env bash
 
+DIR=${0%/*}
+if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
+cd $DIR
+
 if [ "$#" -ne 1 ] ; then
-   echo "========= MOCK SLURM sbatch =========="
-   echo "usage sbatch SubmitScript"
+   echo "========= MOCK SLURM scancel =========="
+   echo "usage scancel jobnumber"
    exit 1;
 fi
 
-job=$1
+jobid=$1
 
-jobid=$(( ( RANDOM % 1000 )  + 42000000000 ))
+if [ ! -e "$DIR/slurm-$jobid.pid" ]; then
+   echo "process id file not found"
+   exit 1;
+fi
 
-#
-# sbatch /share/apps/vcell3/htclogs/V_TEST_116065096_0_96.slurm.sub
-# Submitted batch job 155527
-#
-(
-  #
-  # spawn new process for the job
-  # 
-  echo "job dispatched $jobid"
-  echo $jobid >> slurm.jobid
-  echo "starting job $jobid on Vagrant singularity box"
-  ../../docker/singularity-vm/run.sh $job
-  retcode=$?
-  if [[ $retcode -ne 0 ]]; then
-     echo "job failed"
-     exit $retcode
-  else
-     echo "job $jobid ended"
-     exit 0
-  fi
-) >>/Users/schaff/Documents/workspace-modular/vcell/deploy/mockslurm/slurm.log 2>&1 &
+pid=$(cat $DIR/slurm-$jobid.pid)
 
-echo Submitted batch job $jobid
-exit 0
+kill -9 $pid
+if [[ $? -ne 0 ]]; then
+   echo "job $jobid does not exist"
+   exit 1
+else
+   echo "killed job $jobid"
+   exit 0
+fi
