More context information

diff --git a/.github/workflows/NightlyBMDB_CLI.yml b/.github/workflows/NightlyBMDB_CLI.yml
--- a/.github/workflows/NightlyBMDB_CLI.yml
+++ b/.github/workflows/NightlyBMDB_CLI.yml
@@ -237,19 +237,29 @@ jobs:
           SOURCE_DIR="$GITHUB_WORKSPACE/omex_files"
           TARGET_DIR="$GITHUB_WORKSPACE/set_${{ matrix.sets }}"
           MOD_VALUE=${{ matrix.sets }}
-          file_index=0
           
           # make target dir
           mkdir $TARGET_DIR
           # loop through files in directory, increment indexing and separating files
+          
+          echo "Extracting tests"
+          
           for file in $SOURCE_DIR/*; do
-              file_index=$((file_index+1))
-              if [[ $file == *1008* ]]; then
+              # Is the file of the correct form?
+              base_name=$(basename $file)
+              if ! [[ $base_name =~ ^BIOMD[0-9]+\.omex$ ]]; then
+                echo "Input is invalid. Expecting `BIOMD##########.omex` format, got `${base_name}`."
+                continue
+              fi
+              # ...is it the infamous BioModel 1008?
+              if [[ $base_name == *1008* ]]; then
                   echo -n 'skipping '
-                  echo $file
+                  echo $base_name
                   continue
               fi
-              if [ $((file_index%${{ strategy.job-total }})) -eq $((MOD_VALUE + 0)) ]; then
+              number=$(echo "$base_name" | sed -n 's/^BIOMD\([0-9]\+\)\.omex$/\1/p' | sed 's/^0*//')
+              if [ $((number % ${{ strategy.job-total }})) -eq $((MOD_VALUE + 0)) ]; then
+                  echo "Accepting ${base_name}"
                   cp ${file} $TARGET_DIR/
               fi
           done
@@ -269,7 +279,7 @@ jobs:
                 sim_input="/root/$(basename ${file})"
                 sim_output="/root/$(basename ${base_name})_output"
                 docker run -v $GITHUB_WORKSPACE/set_${{ matrix.sets }}:/root $(docker image ls | grep "<none>" | awk '{print $3;}') execute -d -i $sim_input -o $sim_output --writeLogFiles --guaranteeGoodReturnCode
-            
+                echo -e "\n\n\n\n\n" # give ourselves some line separation
                 # Check for individual Success
                 if [ $(find $GITHUB_WORKSPACE/set_${{ matrix.sets }} -name errorLog.txt | wc -l) -ne 0 ]
                 then
@@ -290,6 +300,8 @@ jobs:
           then
             exit 0
           fi
+          echo "Models that failed:"
+          cat ${{ github.workspace }}/errors.report
 
       - name: Upload failures
         uses: actions/upload-artifact@v3
